### ISSUE TITLE
Redesign User Dashboard and Category/Task Selection

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#328]
## Expected Behavior

MedTagger should use new look and feel on the dashboard page.

## Tasks to do

- [ ] Design for User Dashboard on Figma,
- [ ] Design for Category/Task Selection on Figma,
- [ ] Implementation - CSS/HTML/JS.

**Comment by kolszewska** [comment]
Isn't it kind of done? Or do we mean to make the dashboard more extra :star: ?
