### ISSUE TITLE
Publish MedTagger to the PyPi

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#340]
## Current Behavior

MedTagger's GitHub repository has to be cloned each time user wants to set up or update his/her MedTagger instance.

## Expected Behavior

MedTagger should be available in the PyPi. It should be installable by:
```bash
$> pip install medtagger
```

## Tasks to do

- [ ] Prepare Makefile entrypoint which will build distribution package.
- [ ] Prepare Makefile entrypoint which will publish package to the PyPi.
- [ ] Test whole setup with https://test.pypi.org before publishing to the official repository.

## Additional comment (optional)

This Issue bases on POC #315. Please contact with @jpowie01 before you start working on this!
