### ISSUE TITLE
Enable E2E tests automation on Travis CI

### ISSUE THREAD

**Issue by jpowie01** [jpowie01/MedTagger#456]
## Current Behavior

We've got E2E tests but they can only be run on a local setup.

## Expected Behavior

E2E tests should run after each commit merge to master and on schedule (eg. each day at midnight).

## Tasks to do

- [ ] Prepare separate Docker-Compose configuration for E2E Tests
- [ ] Automate setup and tests in similar fashion that it is currently done in Backend functional tests
- [ ] Add E2E Tests to Travis CI configuration
- [ ] Update documentation for testing
